### ISSUE TITLE
Dataset Consulting

### ISSUE THREAD

**Issue by CodingNovice7** [yunshengtian/Assemble-Them-All#3]
Your open source dataset is generated based on Fusion 360 Gallery, so is it possible to provide a way to find the file corresponding to this assembly in Fusion 360 Gallery by one of the assemblies in this dataset?

**Comment by yunshengtian** [comment]
Sorry currently I don't have that correspondence saved. I might be able to generate that but it's not guaranteed - I need to try.

**Comment by CodingNovice7** [comment]
> Sorry currently I don't have that correspondence saved. I might be able to generate that but it's not guaranteed - I need to try.


Thanks for your prompt answer!
Then using your method to input data from Fusion 360 Gallery should give you the appropriate assembly motion and sequence, right?

**Comment by yunshengtian** [comment]
Yes if your assembly meshes are arranged in a particular way - see our dataset for examples. Basically, you need to name the meshes as `0-N.obj`, and since their geometry information may be defined in their local coordinate frame so you need to provide a `translation.json` that specifies the translation to their global assembled position.

This is a good question and I think this specific requirement may cause some headache. Let me see if I can make things easier to work with.

**Comment by CodingNovice7** [comment]
Ok, I would still like to provide the open source dataset corresponding to the Fusion 360 Gallery file index if it is convenient, but if it is difficult, forget it.
Thank you very much, I'll close this issue now.

**Comment by yunshengtian** [comment]
Thank you for your patience. I finally figured out how I generated that, and [here](https://drive.google.com/file/d/1glBb9x2fVLJqs7K4GSvivZ6uWMT1aXRh/view?usp=share_link) is the index mapping {our_id: Fusion_360_id}. Hope it helps!

**Comment by CodingNovice7** [comment]
> Thank you for your patience. I finally figured out how I generated that, and [here](https://drive.google.com/file/d/1glBb9x2fVLJqs7K4GSvivZ6uWMT1aXRh/view?usp=share_link) is the index mapping {our_id: Fusion_360_id}. Hope it helps!

Thanks for the data and the program, I've noticed your work since joinable and am very much looking forward to your next result!

**Comment by yunshengtian** [comment]
Thank you! Yes please stay tuned - we are indeed working on more exciting things :)

**Comment by CodingNovice7** [comment]
> 

Haha, I'm really looking forward to it!

**Comment by CodingNovice7** [comment]
> Yes if your assembly meshes are arranged in a particular way - see our dataset for examples. Basically, you need to name the meshes as `0-N.obj`, and since their geometry information may be defined in their local coordinate frame so you need to provide a `translation.json` that specifies the translation to their global assembled position.
> 

I'm sorry I'm back, as I am having some problems reproducing your dataset using Fusion360 and would like to get your help. Is the N of 0-N here the assembly sequence of the parts in your given dataset? How was this sequence derived? Regarding translations where you give each part a 3D vector, is this vector the initial coordinates of the part in the simulator? Why is it not a pose matrix? And how do you get the coordinates?

**Comment by yunshengtian** [comment]
> Is the N of 0-N here the assembly sequence of the parts in your given dataset?

No 0-N does not mean a sequence, I simply mean you have to name the files as numbers (even don't need to start with 0 and end with N). 

> Regarding translations where you give each part a 3D vector, is this vector the initial coordinates of the part in the simulator?

Yes.

> Why is it not a pose matrix? 

Sure pose matrix is more general. But in our dataset, the parts are already in the right orientation so we only used the translation vectors to keep it simple.

> And how do you get the coordinates?

From the Fusion 360 dataset.

**Comment by CodingNovice7** [comment]
So the coordinates in the translation.json file are the translation vectors in the pose matrix in Fusion 360 data?

**Comment by yunshengtian** [comment]
Right if I remember correctly.

**Comment by CodingNovice7** [comment]
Ok, thank you!

**Comment by ttsesm** [comment]
Apologies for jumping in your issue but I am trying to understand as well how the whole thing works.... So one naive question, is it possible to extract the R|t transformation matrix that puts the two pieces together?

**Comment by CodingNovice7** [comment]
> Apologies for jumping in your issue but I am trying to understand as well how the whole thing works.... So one naive question, is it possible to extract the R|t transformation matrix that puts the two pieces together?

As I understand it you should be entering an assembled assembly, the dataset here is from Fusion 360 and that dataset contains the assembly poses of the part, which I think is what you want.

**Comment by ttsesm** [comment]
@lylwy Thanks for your time to respond ;-)

Ok to make things a bit more clear, for example I am trying to figure out if this work could be used for the [Breading bad](https://breaking-bad-dataset.github.io/) dataset. (I also opened an issue [here](https://github.com/yunshengtian/Assemble-Them-All/issues/4) in case you want to continue there so that we do not hijack this issue).

The breaking bad dataset comes also with multiple objects already fractured from 2-100 pieces, e.g. the following bowl:
Full model:
![image](https://user-images.githubusercontent.com/10189018/220152002-8017499b-19d7-4500-9205-d0b50e8b61db.png)
Piece 1:
![image](https://user-images.githubusercontent.com/10189018/220152315-d3d59fec-317f-4a08-9836-8b4eb1bb12a4.png)
Piece 2:
![image](https://user-images.githubusercontent.com/10189018/220152368-545a219f-2456-450d-bde3-7b272ed7455a.png)
Piece3:
![image](https://user-images.githubusercontent.com/10189018/220152431-af781324-b7fc-46b7-b747-cd0f2552f6aa.png)
Piece 4:
![image](https://user-images.githubusercontent.com/10189018/220152476-f69c3af8-080d-4cae-94e4-f11c202b5888.png)
Piece 5:
![image](https://user-images.githubusercontent.com/10189018/220152525-919d8e19-3370-4865-813e-a484fb030d0e.png)

So in principle I have already the assembled format, and in principle using this work I should be able to obtain the motion plan for assebly/disassembly. My goal though is to obtain the transformation matrices that given as input the individual pieces they give me back the assembled model. Thus, from the motion plan I should be able to obtain this information, shouldn't I? Or I am missing something?

[fractured_2.zip](https://github.com/yunshengtian/Assemble-Them-All/files/10785996/fractured_2.zip)

**Comment by yunshengtian** [comment]
This should be doable and please see my response in #4

**Comment by Zywooooo** [comment]
> > Apologies for jumping in your issue but I am trying to understand as well how the whole thing works.... So one naive question, is it possible to extract the R|t transformation matrix that puts the two pieces together?抱歉跳进你的问题，但我也想弄明白整个过程是怎么运作的......有个天真的问题，有没有可能提取出将两部分结合起来的 R|t 变换矩阵？
> 
> As I understand it you should be entering an assembled assembly, the dataset here is from Fusion 360 and that dataset contains the assembly poses of the part, which I think is what you want.据我了解，你应该输入一个已组装好的装配体，这里的数据集来自 Fusion 360，里面包含了零件的装配姿态，我觉得这正是你想要的。

I have a question. May I ask if you also use the assembly dataset from Fusion360 as the basis to obtain a dataset with assembly sequence? Have you succeeded, bro?
